# Generated by Django 5.1 on 2024-09-04 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('addate', models.DateField()),
                ('dob', models.DateField()),
                ('year', models.CharField(default='I', max_length=10)),
                ('fathername', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=10)),
                ('transport', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=20)),
                ('hostel', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=20)),
                ('photo', models.ImageField(upload_to='image/')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.department')),
            ],
        ),
    ]
