# Generated by Django 5.1 on 2024-09-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_student_batch_alter_student_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.IntegerField()),
                ('eligibility', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('course_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.courselevel')),
            ],
        ),
    ]
