# Generated by Django 5.1.1 on 2024-09-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_student_course_fees_student_total_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='paid_course_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='paid_hostel_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='paid_transport_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pending_course_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pending_hostel_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pending_transport_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
