# Generated by Django 5.1.1 on 2024-09-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_student_paid_course_fees_student_paid_hostel_fees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='paid_course_fees',
        ),
        migrations.RemoveField(
            model_name='student',
            name='paid_hostel_fees',
        ),
        migrations.RemoveField(
            model_name='student',
            name='paid_transport_fees',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pending_course_fees',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pending_hostel_fees',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pending_transport_fees',
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paidamount', models.IntegerField()),
                ('paiddate', models.DateField()),
                ('feestype', models.CharField(max_length=50)),
                ('student_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.student')),
            ],
        ),
    ]
