# Generated by Django 5.1.1 on 2024-09-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_remove_student_paid_course_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pending_course',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pending_hostel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pending_trasport',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='total_pending',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
